#!/bin/env bash

# Install nginx on your web-01
sudo apt-get -y update
sudo apt-get install -y nginx

#nginx listen to port 80
ufw allow 'Nginx HTTP'

#default page
echo "Hello World" > /var/www/html/index.html

#restart nginx
sudo service nginx restart
