#!/usr/bin/env bash

#displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" before "Best School".
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    ((counter++))
done
