#!/usr/bin/env bash

#displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59


while [ $hours -le 12 ]
do
    minutes=1
    while [ $minutes -le 59 ]
    do
        printf "%02d:%02d\n" $hours $minutes
        ((minutes++))
        if [ $minutes -gt 59 ]; then
            break
        fi
    done
    ((hours++))
done | head -n 70

