#!/usr/bin/env bash

#displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hour=0
while [ $hours -le 12 ]
do
    echo "Hour: hours"
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((hours++))
done

