#!/usr/bin/env bash

for file in *
do
    if [ -f "$file" ] && [[ "$file" != .* ]]  # Check if it's a file and not hidden
    then
        name=$(echo "$file" | cut -d'-' -f2-)  # Extracts part after the first dash
        echo "$name"
    fi
done

