#!/usr/bin/env bash

#displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

do
    if [ -f "$file" ] && [[ "$file" != .* ]]  # Check if it's a file and not hidden
    then
        name=$(echo "$file" | cut -d'-' -f2-)  # Extracts part after the first dash
        echo "$name"
    fi
done

